version: "2.1"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./DockerfileDev
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/src/:/app/
    ports:
      - 9000:9000

  static:
    image: nginx:latest
    restart: always
    volumes:
      - ./backend/src/static/:/app/static
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080

volumes:
  frontend_node_modules:
