version: "2.1"

services:
  backend-blue:
    image: baealex/blex-backend
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/src/db.sqlite3:/app/db.sqlite3
      - ./backend/src/resources/media:/app/resources/media
    networks:
      - blex-network

  nginx-blue:
    image: baealex/blex-nginx
    restart: always
    volumes:
      - ./backend/src/resources/media:/resources/media
    ports:
      - 20002:80
    depends_on:
      - backend-blue
    environment:
      - BACKEND_HOST=backend-blue
    networks:
      - blex-network

networks:
  blex-network:
    driver: bridge
