version: "2.0"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./DockerfileDev
    restart: always
    volumes:
      - ./frontend/src/:/app/
      - /app/node_modules/
    ports:
      - 3000:3000
  
  backend:
    build:
      context: ./backend
      dockerfile: ./DockerfileDev
    restart: always
    environment:
      TZ: "Asia/Seoul"
      LANG: "C.UTF-8"
    volumes:
      - ./backend/src/:/app/
    ports:
      - 9000:9000