version: "2.0"

services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./server/src/uwsgi_params:/www/uwsgi_params
  #     - ./server/src/static:/www/static
  #     - ./server/src/api:/www/api
  #   ports:
  #     - 20000:20000
  #     - 20200:20200

  api_app:
    image: richarvey/nginx-php-fpm
    volumes:
      - ./server/src/api:/var/www/html
    ports:
      - 20300:80
  
  app:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./server/src/:/app/
    ports:
      - 9000:9000