version: "2.0"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file: ./frontend/.env
    restart: always
    ports:
      - 20011:3000
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend/src/:/app/
    ports:
      - 20012:9000