version: "2.0"

services:
  frontend:
    image: baealex/blex-frontend
    env_file: ./frontend/.env
    restart: always
    ports:
      - 20011:3000
  
  backend:
    image: baealex/blex-backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend/src/:/app/
    ports:
      - 20012:9000