version: "2.0"

services:
  # 개발 상태인 경우 주석 해제
  # webserver:
  #   image: nginx
  #   volumes:
  #     - ./webserver/nginx.conf:/etc/nginx/nginx.conf
  #     - ./backend/src/uwsgi_params:/www/uwsgi_params
  #     - ./backend/src/static:/www/static
  #     - ./backend/src/api:/www/api
  #   ports:
  #     - 20201:20001
  #     - 20202:20002
  #     - 20203:20003
  
  # 개발 상태인 경우 주석 해제
  frontend:
    build:
      context: ./frontend
    # volumes:
    #   - /app/node_modules
    #   - ./frontend/src/:/app/
    # command:
    #   - "dev"
    ports:
      - 20001:3000
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src/:/app/
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - 20002:9000