services:
  blex:
    image: baealex/blex
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/src/db.sqlite3:/app/db.sqlite3
      - ./backend/src/resources/media:/app/resources/media
    ports:
      - 20002:80
