version: "2.0"

services:
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: ./DockerfileDev
    env_file: ./frontend/.env
    restart: always
    volumes:
      - ./frontend/src/:/app/
      - /app/node_modules/
    ports:
      - 3000:3000
  
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: ./DockerfileDev
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/src/:/app/
    ports:
      - 9000:9000
  