version: "2.0"

services:
  # webserver:
  #   image: nginx
  #   volumes:
  #     - ./webserver/nginx.conf:/etc/nginx/nginx.conf
  #     - ./backend/src/uwsgi_params:/www/uwsgi_params
  #     - ./backend/src/static:/www/static
  #     - ./backend/src/api:/www/api
  #   ports:
  #     - 20201:20001
  #     - 20202:20002
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src/pages/:/app/pages/
      - ./frontend/src/public/:/app/public/
      - ./frontend/src/styles/:/app/styles/
      - ./frontend/src/modules/:/app/modules/
      - ./frontend/src/components/:/app/components/
    ports:
      - 20001:3000
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src/:/app/
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - 20002:9000
    
  gfm-api:
    image: richarvey/nginx-php-fpm
    volumes:
      - ./gfm-api:/var/www/html
    ports:
      - 20003:80