version: "2.1"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./DockerfileDev
    env_file: ./frontend/.env
    restart: always
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/src/package.json:/app/package.json
      - ./frontend/src/package-lock.json:/app/package-lock.json
      - frontend_node_modules:/app/node_modules
    ports:
      - 3000:3000
  
  backend:
    build:
      context: ./backend
      dockerfile: ./DockerfileDev
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/src/:/app/
    ports:
      - 9000:9000
  
  static:
    image: nginx:latest
    restart: always
    volumes:
      - ./backend/src/static/:/app/static
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080

volumes:
  frontend_node_modules:
