version: "2.0"

services:
  # image: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./server/src/uwsgi_params:/www/uwsgi_params
  #     - ./server/src/static:/www/static
  #     - ./server/src/api:/www/api
  #   ports:
  #     - 20000:20000
  #     - 20200:20200
  #     - 20300:20300
  # 
  # php:
  #   image: php:fpm
    
  app:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./server/src/static:/app/static
      - ./server/src/dump.json:/app/dump.json
      - ./server/src/db.sqlite3:/app/db.sqlite3
    ports:
      - 9000:9000