version: "2.0"

services:
  frontend:
    platform: linux/amd64
    image: baealex/blex-frontend
    env_file: ./frontend/.env
    restart: always
    ports:
      - 20001:3000
  
  backend:
    platform: linux/amd64
    image: baealex/blex-backend
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/src/:/app/
    ports:
      - 20002:9000
