version: "2.0"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 20011:3000
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      TZ: "Asia/Seoul"
      LANG: "C.UTF-8"
    volumes:
      - ./backend/src/:/app/
    ports:
      - 20012:9000