import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chokidar from 'chokidar';
import { glob } from 'glob';

// __dirname equivalent in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths
const TEMPLATES_DIR = path.resolve(__dirname, '../../../../src/board/templates');
const SCSS_OUTPUT_FILE = path.resolve(__dirname, '../styles/forwarded.scss');
const ALPINE_OUTPUT_FILE = path.resolve(__dirname, '../src/scripts/alpine-loader.ts');

const updateScssParams = {
    pattern: '**/*.scss',
    outputFile: SCSS_OUTPUT_FILE,
    header: '// Auto-generated by scripts/watch-assets.js. Do not edit manually.\n',
    generateContent: (files) => {
        return files.map(file => `@forward "@templates/${file}";`).join('\n') + '\n';
    }
};

const updateAlpineParams = {
    // Only look for *.alpine.ts files
    pattern: '**/*.alpine.ts',
    outputFile: ALPINE_OUTPUT_FILE,
    header: '// Auto-generated by scripts/watch-assets.js. Do not edit manually.\nimport Alpine from \'alpinejs\';\n\n',
    generateContent: (files) => {
        const lines = files.map((file, index) => {
            const importName = `alpineModule${index}`;
            const basename = path.basename(file, '.alpine.ts');
            return {
                import: `import ${importName} from '@templates/${file}';`,
                registration: `Alpine.data('${basename}', ${importName});`
            };
        });

        const imports = lines.map(l => l.import).join('\n');
        const registrations = lines.map(l => l.registration).join('\n');

        const footer = `

// Alpine Init
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => Alpine.start());
} else {
    Alpine.start();
}

window.Alpine = Alpine;

export default Alpine;
`;

        return imports + '\n\n' + registrations + footer;
    }
};

const updateAssets = async (type) => {
    const params = type === 'scss' ? updateScssParams : updateAlpineParams;

    try {
        const files = await glob(params.pattern, { cwd: TEMPLATES_DIR });

        files.sort();

        const content = params.generateContent(files);
        const fileContent = params.header + content;

        fs.writeFileSync(params.outputFile, fileContent);
        console.log(`[watch-assets] Updated ${path.basename(params.outputFile)} with ${files.length} files.`);
    } catch (error) {
        console.error(`[watch-assets] Error updating ${type}:`, error);
    }
};

const watch = () => {
    if (!fs.existsSync(TEMPLATES_DIR)) {
        console.warn(`[watch-assets] Templates directory not found: ${TEMPLATES_DIR}`);
        return;
    }

    console.log(`[watch-assets] Watching ${TEMPLATES_DIR}...`);

    // Initial sync
    updateAssets('scss');
    updateAssets('alpine');

    const watcher = chokidar.watch(TEMPLATES_DIR, {
        ignored: /(^|[/\\])\../, // ignore dotfiles
        persistent: true,
        ignoreInitial: true // we did initial sync manually
    });

    watcher.on('all', (event, filePath) => {
        // Check extension
        if (filePath.endsWith('.scss')) {
            updateAssets('scss');
        } else if (filePath.endsWith('.alpine.ts')) {
            updateAssets('alpine');
        }
    });

    watcher.on('error', error => console.error(`[watch-assets] Watcher error: ${error}`));
};

watch();
