# Generated by Django 4.0.7 on 2022-09-14 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='agree_editor',
        ),
        migrations.RemoveField(
            model_name='config',
            name='agree_email',
        ),
        migrations.RemoveField(
            model_name='config',
            name='agree_history',
        ),
        migrations.RemoveField(
            model_name='config',
            name='password_qna',
        ),
        migrations.RemoveField(
            model_name='config',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='series',
            name='index',
        ),
        migrations.AlterField(
            model_name='userconfigmeta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conf_meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
