# Generated by Django 4.0.7 on 2022-10-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_config_agree_editor_remove_config_agree_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
