# Generated by Django 4.2 on 2023-04-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
