# Generated by Django 4.2.7 on 2023-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_usernamechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinkmeta',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserProfileLayout',
        ),
    ]
