# Generated by Django 4.2.7 on 2023-11-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_remove_profile_facebook_remove_profile_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('headers', models.TextField(blank=True)),
                ('payload', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.developertoken')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('extra_data', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAuthProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='edithistory',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='editrequest',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='notify',
            old_name='infomation',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notify',
            old_name='is_read',
            new_name='has_read',
        ),
        migrations.RenameField(
            model_name='postanalytics',
            old_name='table',
            new_name='devices',
        ),
        migrations.RenameField(
            model_name='postanalytics',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postconfig',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postcontent',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postnothanks',
            old_name='history',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='postthanks',
            old_name='history',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='referer',
            old_name='posts',
            new_name='analytics',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reporter',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='searcher',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='twofactorauth',
            old_name='one_pass_token',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='twofactorauth',
            old_name='one_pass_token_exp',
            new_name='otp_exp_date',
        ),
        migrations.AddField(
            model_name='imagecache',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referer',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.post'),
        ),
        migrations.RenameModel(
            old_name='History',
            new_name='Device',
        ),
        migrations.DeleteModel(
            name='DeveloperTokenLog',
        ),
        migrations.AddField(
            model_name='socialauth',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.socialauthprovider'),
        ),
        migrations.AddField(
            model_name='socialauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developerrequestlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.device'),
        ),
    ]
