# Generated by Django 4.2.7 on 2023-12-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_developerrequestlog_socialauth_socialauthprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchvalue',
            name='reference_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='board.searchvalue'),
        ),
    ]
