# Generated by Django 5.1.5 on 2025-03-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_remove_postconfig_pinned_alter_invitation_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaiusagehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='OpenAIConnection',
        ),
        migrations.DeleteModel(
            name='OpenAIUsageHistory',
        ),
    ]
