# Generated by Django 5.1.14 on 2025-11-16 00:17

from django.db import migrations, models


def create_sitesetting_instance(apps, schema_editor):
    """Create the singleton SiteSetting instance if it doesn't exist."""
    SiteSetting = apps.get_model('board', 'SiteSetting')
    if not SiteSetting.objects.filter(pk=1).exists():
        SiteSetting.objects.create(
            pk=1,
            header_script='',
            footer_script=''
        )


def reverse_create_sitesetting_instance(apps, schema_editor):
    """Remove the SiteSetting instance."""
    SiteSetting = apps.get_model('board', 'SiteSetting')
    SiteSetting.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_remove_openaiusagehistory_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_script', models.TextField(blank=True, help_text='<head> 태그 안에 삽입될 스크립트 (예: Google Analytics, Umami)')),
                ('footer_script', models.TextField(blank=True, help_text='</body> 태그 전에 삽입될 스크립트')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='postnothanks',
            name='device',
        ),
        migrations.RemoveField(
            model_name='developerrequestlog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='postthanks',
            name='device',
        ),
        migrations.RemoveField(
            model_name='report',
            name='device',
        ),
        migrations.RemoveField(
            model_name='search',
            name='device',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invitationrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='invitationrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='postanalytics',
            name='post',
        ),
        migrations.RemoveField(
            model_name='referer',
            name='analytics',
        ),
        migrations.RemoveField(
            model_name='postnothanks',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postthanks',
            name='post',
        ),
        migrations.RemoveField(
            model_name='referer',
            name='post',
        ),
        migrations.RemoveField(
            model_name='referer',
            name='referer_from',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='search',
            name='search_value',
        ),
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.AddField(
            model_name='developerrequestlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User agent string', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='analytics_share_url',
            field=models.URLField(blank=True, help_text='분석 도구 공유 URL (예: Umami, Google Analytics 등)', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('READER', '독자'), ('EDITOR', '편집자'), ('ADMIN', '관리자')], default='READER', help_text='사용자 역할 (독자: 읽기만, 편집자: 글 작성 및 통계, 관리자: 전체 관리)', max_length=10),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='InvitationRequest',
        ),
        migrations.DeleteModel(
            name='PostAnalytics',
        ),
        migrations.DeleteModel(
            name='PostNoThanks',
        ),
        migrations.DeleteModel(
            name='PostThanks',
        ),
        migrations.DeleteModel(
            name='Referer',
        ),
        migrations.DeleteModel(
            name='RefererFrom',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SearchValue',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.RunPython(
            create_sitesetting_instance,
            reverse_create_sitesetting_instance
        ),
    ]
