# Generated by Django 5.1.14 on 2025-11-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_sitesetting_remove_postnothanks_device_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL 경로 (예: about, privacy, terms)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='페이지 제목', max_length=200)),
                ('content', models.TextField(help_text='페이지 내용 (HTML 지원)')),
                ('meta_description', models.CharField(blank=True, help_text='SEO용 메타 설명 (최대 160자)', max_length=160)),
                ('is_published', models.BooleanField(default=True, help_text='공개 여부')),
                ('show_in_footer', models.BooleanField(default=False, help_text='푸터에 링크 표시')),
                ('order', models.IntegerField(default=0, help_text='정렬 순서 (낮을수록 먼저)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '정적 페이지',
                'verbose_name_plural': '정적 페이지',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
