# Generated by Django 5.1.14 on 2025-11-18 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='공지 제목', max_length=200)),
                ('url', models.CharField(help_text='공지 클릭 시 이동할 URL', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': '# Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='welcome_notification_message',
            field=models.TextField(blank=True, default='', help_text='회원가입 시 발송될 환영 알림 메시지 ({name}을 사용하여 사용자 이름 삽입 가능)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='welcome_notification_url',
            field=models.CharField(blank=True, default='/', help_text='회원가입 알림 클릭 시 이동할 URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('READER', '독자'), ('EDITOR', '편집자')], default='READER', help_text='사용자 역할 (독자: 읽기만, 편집자: 글 작성)', max_length=10),
        ),
    ]
