# Generated by Django 5.1.14 on 2025-11-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_globalnotice_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='account_deletion_redirect_url',
            field=models.CharField(blank=True, default='', help_text='회원 탈퇴 시 리다이렉트할 URL (비워두면 메인 페이지로 이동, 설문 링크 등을 설정할 수 있습니다)', max_length=500),
        ),
    ]
