# Generated by Django 5.1.14 on 2025-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_globalnotice_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='BLEX', help_text='사이트 이름 (영문)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_korean',
            field=models.CharField(default='블렉스', help_text='사이트 이름 (한글)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_description',
            field=models.CharField(blank=True, default='BLOG EXPRESS ME', help_text='사이트 설명 (RSS 피드 등에 사용)', max_length=200),
        ),
    ]
