# Generated by Django 5.1.14 on 2026-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_sitesetting_account_deletion_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_top_html',
            field=models.TextField(blank=True, help_text='블로그 상단에 표시될 배너 HTML (스크립트는 제거됨)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_bottom_html',
            field=models.TextField(blank=True, help_text='블로그 하단에 표시될 배너 HTML (스크립트는 제거됨)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_enabled',
            field=models.BooleanField(default=False, help_text='배너 표시 여부'),
        ),
    ]
