# Generated by Django 5.1.14 on 2025-11-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_sitesetting_account_deletion_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='otp_exp_date',
        ),
    ]
