# Generated by Claude on 2025-11-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0021_twofactorauth_totp_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='웹훅 이름', max_length=100)),
                ('url', models.URLField(help_text='웹훅 URL', max_length=500)),
                ('provider', models.CharField(default='generic', help_text='웹훅 제공자 (generic, discord, slack)', max_length=20)),
                ('events', models.JSONField(default=list, help_text='구독할 이벤트 목록')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('secret', models.CharField(blank=True, help_text='웹훅 서명용 시크릿', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='이벤트 타입', max_length=50)),
                ('payload', models.TextField(help_text='전송한 페이로드')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP 응답 코드', null=True)),
                ('response', models.TextField(blank=True, help_text='응답 내용')),
                ('error', models.TextField(blank=True, help_text='에러 메시지')),
                ('retry_count', models.IntegerField(default=0, help_text='재시도 횟수')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.developerwebhook')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
