# Generated by Django 5.1.14 on 2026-01-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='배너 이름 (관리용)', max_length=100)),
                ('content_html', models.TextField(help_text='배너 HTML 콘텐츠 (스크립트는 자동 제거됨)')),
                ('banner_type', models.CharField(choices=[('horizontal', '줄배너 (가로 전체)'), ('sidebar', '사이드배너 (좌우 측면)')], default='horizontal', help_text='배너 타입', max_length=20)),
                ('position', models.CharField(choices=[('top', '상단'), ('bottom', '하단'), ('left', '좌측'), ('right', '우측')], default='top', help_text='배너 위치', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='배너 활성화 여부')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_date'],
                'indexes': [
                    models.Index(fields=['user', 'is_active', 'position'], name='board_banne_user_id_9e8a6f_idx'),
                ],
            },
        ),
    ]
