# Generated by Django 6.0 on 2026-01-12 14:54

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('board', '0023_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityProxy',
            fields=[
            ],
            options={
                'verbose_name': '유틸리티 관리',
                'verbose_name_plural': '유틸리티 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='banner',
            new_name='board_banne_user_id_e3e1e2_idx',
            old_name='board_banne_user_id_9e8a6f_idx',
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('READER', '독자'), ('EDITOR', '편집자')], default='READER', help_text='사용자 역할 (독자: 읽기만, 편집자: 글 작성 및 통계)', max_length=10),
        ),
    ]
