# Generated by Django 6.0.1 on 2026-02-04 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_utilityproxy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_date'], name='board_comme_post_id_260f64_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_date'], name='board_comme_author__e4042f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_date'], name='board_post_author__effd83_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_date'], name='board_post_created_69fd60_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['url'], name='board_post_url_7e049a_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikes',
            index=models.Index(fields=['post', 'user'], name='board_post__post_id_ce5821_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikes',
            index=models.Index(fields=['user', 'created_date'], name='board_post__user_id_44c70b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['value'], name='board_tag_value_caa644_idx'),
        ),
        migrations.AddIndex(
            model_name='usernamechangelog',
            index=models.Index(fields=['username'], name='board_usern_usernam_873004_idx'),
        ),
    ]
