# Generated by Django 6.0.2 on 2026-02-04 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_comment_board_comme_post_id_260f64_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developertoken',
            name='user',
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(help_text='Webhook URL (Discord, Slack, etc.)', max_length=500)),
                ('name', models.CharField(blank=True, help_text='Optional name/description for this subscription', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Consecutive webhook delivery failures')),
                ('last_success_date', models.DateTimeField(blank=True, help_text='Last successful webhook delivery', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(help_text='The author being subscribed to', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscribers', to='board.profile')),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('author', 'webhook_url')},
            },
        ),
        migrations.DeleteModel(
            name='DeveloperRequestLog',
        ),
        migrations.DeleteModel(
            name='DeveloperToken',
        ),
    ]
