# Generated by Django 6.0.2 on 2026-02-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_remove_developertoken_user_webhooksubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='배너 이름 (관리용)', max_length=100)),
                ('content_html', models.TextField(help_text='배너 HTML 콘텐츠 (관리자 전용 - sanitize 없음)')),
                ('banner_type', models.CharField(choices=[('horizontal', '줄배너 (가로 전체)'), ('sidebar', '사이드배너 (좌우 측면)')], default='horizontal', help_text='배너 타입', max_length=20)),
                ('position', models.CharField(choices=[('top', '상단'), ('bottom', '하단'), ('left', '좌측'), ('right', '우측')], default='top', help_text='배너 위치', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='배너 활성화 여부')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🏢 [사이트 운영] 글로벌 배너',
                'verbose_name_plural': '🏢 [사이트 운영] 글로벌 배너',
                'ordering': ['order', '-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='globalnotice',
            options={'ordering': ['-created_date'], 'verbose_name': '🏢 [사이트 운영] 글로벌 공지', 'verbose_name_plural': '🏢 [사이트 운영] 글로벌 공지'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '🏢 [사이트 운영] 사이트 설정', 'verbose_name_plural': '🏢 [사이트 운영] 사이트 설정'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['order', 'slug'], 'verbose_name': '🏢 [사이트 운영] 정적 페이지', 'verbose_name_plural': '🏢 [사이트 운영] 정적 페이지'},
        ),
        migrations.RemoveIndex(
            model_name='banner',
            name='board_banne_user_id_e3e1e2_idx',
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['user', 'is_active', 'banner_type', 'position'], name='board_banne_user_id_b545b3_idx'),
        ),
        migrations.AddField(
            model_name='globalbanner',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='생성한 관리자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_global_banners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='globalbanner',
            index=models.Index(fields=['is_active', 'banner_type', 'position'], name='board_globa_is_acti_abde4d_idx'),
        ),
    ]
