# Generated by Django 6.0.2 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_globalbanner_alter_globalnotice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
