# Generated by Django 6.0.2 on 2026-02-10 21:38

from django.conf import settings
from django.db import migrations, models


def backfill_published_date(apps, schema_editor):
    """Set published_date = created_date for all existing posts."""
    Post = apps.get_model('board', 'Post')
    Post.objects.filter(published_date__isnull=True).update(
        published_date=models.F('created_date')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_add_post_subtitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_published_date, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published_date'], name='board_post_publish_950f79_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'published_date'], name='board_post_author__54dd01_idx'),
        ),
    ]
