# Generated by Django 6.0.2 on 2026-02-10 21:45

import random
import string

from django.db import migrations
from django.utils.text import slugify


def generate_random_suffix(length=6):
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))


def migrate_temp_posts_to_drafts(apps, schema_editor):
    TempPosts = apps.get_model('board', 'TempPosts')
    Post = apps.get_model('board', 'Post')
    PostContent = apps.get_model('board', 'PostContent')
    PostConfig = apps.get_model('board', 'PostConfig')
    Tag = apps.get_model('board', 'Tag')

    for temp in TempPosts.objects.all():
        # Generate URL from title
        base_url = slugify(temp.title, allow_unicode=True) if temp.title else ''
        if not base_url:
            base_url = f'draft-{generate_random_suffix(8)}'

        url = base_url
        while Post.objects.filter(author=temp.author, url=url).exists():
            url = f'{base_url}-{generate_random_suffix()}'

        # Create Post as draft (published_date=None)
        post = Post.objects.create(
            author=temp.author,
            title=temp.title or '',
            url=url,
            meta_description='',
            created_date=temp.created_date,
            updated_date=temp.updated_date,
            published_date=None,
        )

        # Create PostContent
        PostContent.objects.create(
            post=post,
            text_md=temp.text_md or '',
            text_html=temp.text_md or '',
        )

        # Create PostConfig
        PostConfig.objects.create(
            post=post,
            hide=False,
            notice=False,
            advertise=False,
        )

        # Migrate tags (CSV string → M2M)
        if temp.tag:
            tag_names = [t.strip() for t in temp.tag.split(',') if t.strip()]
            for tag_name in tag_names:
                tag_obj, _ = Tag.objects.get_or_create(value=tag_name)
                post.tag.add(tag_obj)


def reverse_migration(apps, schema_editor):
    # No reverse needed - TempPosts data will still exist
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_add_published_date_to_post'),
    ]

    operations = [
        migrations.RunPython(
            migrate_temp_posts_to_drafts,
            reverse_code=reverse_migration,
        ),
        migrations.DeleteModel(
            name='TempPosts',
        ),
    ]
