# Generated by Django 6.0.2 on 2026-02-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_migrate_temp_posts_to_drafts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilityProxy',
        ),
    ]
