# Generated by Django 6.0.2 on 2026-02-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_migrate_to_site_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banner',
            name='board_banne_user_id_b545b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='globalbanner',
            name='board_globa_is_acti_abde4d_idx',
        ),
        migrations.DeleteModel(
            name='GlobalNotice',
        ),
        migrations.RemoveField(
            model_name='globalbanner',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='GlobalBanner',
        ),
    ]
