# Generated by Django 6.0.2 on 2026-02-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_remove_old_notice_banner_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postconfig',
            name='notice',
        ),
    ]
