# Generated by Django 6.0.2 on 2026-02-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_remove_postconfig_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL 경로 (예: about, privacy, terms)', max_length=100, unique=True),
        ),
    ]
