# Generated by Django 6.0.2 on 2026-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0036_allow_unicode_slug_for_static_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
