# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


def set_global_scope_for_null_author(apps, schema_editor):
    WebhookSubscription = apps.get_model('board', 'WebhookSubscription')
    WebhookSubscription.objects.filter(author__isnull=True).update(scope='global')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0037_post_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='scope',
            field=models.CharField(
                choices=[('user', '사용자'), ('global', '전역')],
                default='user',
                max_length=10
            ),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='author',
            field=models.ForeignKey(
                blank=True,
                help_text='Owner profile for author-specific channel (empty for global channel)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='webhook_subscribers',
                to='board.profile'
            ),
        ),
        migrations.RunPython(set_global_scope_for_null_author, noop_reverse),
        migrations.AlterUniqueTogether(
            name='webhooksubscription',
            unique_together={('scope', 'author', 'webhook_url')},
        ),
    ]
