# Generated by Django 6.0.2 on 2026-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_sitesetting_seo_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='robots_txt_extra_rules',
            field=models.TextField(blank=True, default='', help_text='블로그가 생성하는 robots.txt 기본 정책 뒤에 추가할 런타임 규칙'),
        ),
    ]
