# Generated by Django 6.0.5 on 2026-05-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0046_authorinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('READER', '독자'), ('EDITOR', '작가')], default='READER', help_text='사용자 역할 (독자: 읽기만, 작가: 글 작성 및 통계)', max_length=10),
        ),
    ]
