# Generated by Django 6.0.5 on 2026-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0047_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='postconfig',
            name='cover_image_position',
            field=models.CharField(choices=[('right', '오른쪽'), ('left', '왼쪽')], default='right', max_length=8),
        ),
        migrations.AddField(
            model_name='postconfig',
            name='cover_image_ratio',
            field=models.CharField(choices=[('auto', '원본'), ('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1'), ('3:4', '3:4')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='postconfig',
            name='cover_layout',
            field=models.CharField(choices=[('default', '기본'), ('split', '분할'), ('overlay', '이미지 배경'), ('none', '커버 숨김')], default='default', max_length=16),
        ),
    ]
