# Generated by Django 6.0.7 on 2026-07-14 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_history_metadata(apps, schema_editor):
    EditHistory = apps.get_model('board', 'EditHistory')
    pending = []

    for history in EditHistory.objects.select_related('post').iterator(chunk_size=500):
        history.actor_id = history.post.author_id
        history.source_updated_date = history.created_date
        pending.append(history)

        if len(pending) == 500:
            EditHistory.objects.bulk_update(
                pending,
                ['actor', 'source_updated_date'],
            )
            pending.clear()

    if pending:
        EditHistory.objects.bulk_update(
            pending,
            ['actor', 'source_updated_date'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0056_tag_value_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edithistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_edit_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='change_type',
            field=models.CharField(choices=[('edit', '수정 전'), ('restore', '복원 전'), ('legacy', '레거시')], default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='restored_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_events', to='board.edithistory'),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='source_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            backfill_legacy_history_metadata,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='edithistory',
            name='title',
            field=models.CharField(default='_NO_CHANGED_', max_length=65),
        ),
        migrations.AddIndex(
            model_name='edithistory',
            index=models.Index(fields=['post', 'created_date'], name='board_edith_post_id_50a332_idx'),
        ),
    ]
