# Generated by Django 6.0.7 on 2026-07-14 19:31

from django.db import migrations, models


def prevent_reverse_with_trashed_posts(apps, schema_editor):
    Post = apps.get_model('board', 'Post')
    if Post._base_manager.filter(deleted_date__isnull=False).exists():
        raise RuntimeError(
            '휴지통 포스트를 복구하거나 영구 삭제한 뒤 migration 0058을 되돌려주세요.',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0057_alter_edithistory_options_edithistory_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=prevent_reverse_with_trashed_posts,
        ),
    ]
