# Generated by Django 6.0.7 on 2026-07-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0060_populate_edithistory_content_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '사용자 설정', 'verbose_name_plural': '사용자 설정'},
        ),
        migrations.AlterModelOptions(
            name='edithistory',
            options={'verbose_name': '포스트 수정 이력', 'verbose_name_plural': '포스트 수정 이력'},
        ),
        migrations.AlterModelOptions(
            name='editrequest',
            options={'verbose_name': '포스트 수정 요청', 'verbose_name_plural': '포스트 수정 요청'},
        ),
        migrations.AlterModelOptions(
            name='emailchange',
            options={'verbose_name': '이메일 변경 요청', 'verbose_name_plural': '이메일 변경 요청'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': '사용자 폼', 'verbose_name_plural': '사용자 폼'},
        ),
        migrations.AlterModelOptions(
            name='imagecache',
            options={'verbose_name': '이미지 캐시', 'verbose_name_plural': '이미지 캐시'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name': '알림', 'verbose_name_plural': '알림'},
        ),
        migrations.AlterModelOptions(
            name='pinnedpost',
            options={'verbose_name': '고정 포스트', 'verbose_name_plural': '고정 포스트'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '포스트', 'verbose_name_plural': '포스트'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '프로필', 'verbose_name_plural': '프로필'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': '시리즈', 'verbose_name_plural': '시리즈'},
        ),
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'ordering': ['order', '-created_date'], 'verbose_name': '사이트 배너', 'verbose_name_plural': '사이트 배너'},
        ),
        migrations.AlterModelOptions(
            name='sitenotice',
            options={'ordering': ['order', '-created_date'], 'verbose_name': '사이트 공지', 'verbose_name_plural': '사이트 공지'},
        ),
        migrations.AlterModelOptions(
            name='socialauth',
            options={'verbose_name': '소셜 로그인 연동', 'verbose_name_plural': '소셜 로그인 연동'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterModelOptions(
            name='telegramsync',
            options={'verbose_name': '텔레그램 연동', 'verbose_name_plural': '텔레그램 연동'},
        ),
        migrations.AlterModelOptions(
            name='twofactorauth',
            options={'verbose_name': '2단계 인증', 'verbose_name_plural': '2단계 인증'},
        ),
        migrations.AlterModelOptions(
            name='userconfigmeta',
            options={'verbose_name': '사용자 기능 설정', 'verbose_name_plural': '사용자 기능 설정'},
        ),
        migrations.AlterModelOptions(
            name='userlinkmeta',
            options={'verbose_name': '사용자 링크', 'verbose_name_plural': '사용자 링크'},
        ),
        migrations.AlterModelOptions(
            name='usernamechangelog',
            options={'verbose_name': '사용자명 변경 이력', 'verbose_name_plural': '사용자명 변경 이력'},
        ),
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_date'], 'verbose_name': '웹훅 구독', 'verbose_name_plural': '웹훅 구독'},
        ),
    ]
