# Generated by Django 6.0.7 on 2026-07-17 15:54

from django.db import migrations

# Translations resolve at runtime; migrations retain stable source labels.


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0060_populate_edithistory_content_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'User setting', 'verbose_name_plural': 'User settings'},
        ),
        migrations.AlterModelOptions(
            name='edithistory',
            options={'verbose_name': 'Post revision', 'verbose_name_plural': 'Post revisions'},
        ),
        migrations.AlterModelOptions(
            name='editrequest',
            options={'verbose_name': 'Post edit request', 'verbose_name_plural': 'Post edit requests'},
        ),
        migrations.AlterModelOptions(
            name='emailchange',
            options={'verbose_name': 'Email change request', 'verbose_name_plural': 'Email change requests'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'User form', 'verbose_name_plural': 'User forms'},
        ),
        migrations.AlterModelOptions(
            name='imagecache',
            options={'verbose_name': 'Image cache', 'verbose_name_plural': 'Image caches'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='pinnedpost',
            options={'verbose_name': 'Pinned post', 'verbose_name_plural': 'Pinned posts'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'ordering': ['order', '-created_date'], 'verbose_name': 'Site banner', 'verbose_name_plural': 'Site banners'},
        ),
        migrations.AlterModelOptions(
            name='sitenotice',
            options={'ordering': ['order', '-created_date'], 'verbose_name': 'Site notice', 'verbose_name_plural': 'Site notices'},
        ),
        migrations.AlterModelOptions(
            name='socialauth',
            options={'verbose_name': 'Social login connection', 'verbose_name_plural': 'Social login connections'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='telegramsync',
            options={'verbose_name': 'Telegram connection', 'verbose_name_plural': 'Telegram connections'},
        ),
        migrations.AlterModelOptions(
            name='twofactorauth',
            options={'verbose_name': 'Two-factor authentication', 'verbose_name_plural': 'Two-factor authentication'},
        ),
        migrations.AlterModelOptions(
            name='userconfigmeta',
            options={'verbose_name': 'User feature setting', 'verbose_name_plural': 'User feature settings'},
        ),
        migrations.AlterModelOptions(
            name='userlinkmeta',
            options={'verbose_name': 'User link', 'verbose_name_plural': 'User links'},
        ),
        migrations.AlterModelOptions(
            name='usernamechangelog',
            options={'verbose_name': 'Username change history', 'verbose_name_plural': 'Username change history'},
        ),
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_date'], 'verbose_name': 'Webhook subscription', 'verbose_name_plural': 'Webhook subscriptions'},
        ),
    ]
