# Generated by Django 6.0.7 on 2026-07-18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0061_localize_admin_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityCleanupConfirmation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('session_fingerprint', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='utility_cleanup_confirmations',
                        to='auth.user',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['expires_at'],
                        name='board_utilconfirm_exp_idx',
                    ),
                ],
            },
        ),
    ]
