# Generated by Django 6.0.7 on 2026-08-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0062_utilitycleanupconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edithistory',
            name='change_type',
            field=models.CharField(choices=[('edit', 'Before edit'), ('restore', 'Before restore'), ('legacy', 'Legacy')], default='legacy', max_length=16),
        ),
    ]
