# Generated by Django 6.0.7 on 2026-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0063_localize_revision_change_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postconfig',
            name='cover_image_position',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=8),
        ),
        migrations.AlterField(
            model_name='postconfig',
            name='cover_image_ratio',
            field=models.CharField(choices=[('auto', 'Original'), ('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1'), ('3:4', '3:4')], default='auto', max_length=8),
        ),
        migrations.AlterField(
            model_name='postconfig',
            name='cover_layout',
            field=models.CharField(choices=[('default', 'Default'), ('split', 'Split'), ('overlay', 'Image background'), ('none', 'Hide cover')], default='default', max_length=16),
        ),
    ]
