# Generated by Django 6.0.7 on 2026-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0064_localize_post_cover_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='banner_type',
            field=models.CharField(choices=[('horizontal', 'Full-width banner (horizontal)'), ('sidebar', 'Side banner (left/right)')], default='horizontal', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='top', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='scope',
            field=models.CharField(choices=[('user', 'User'), ('global', 'Global')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sitenotice',
            name='scope',
            field=models.CharField(choices=[('user', 'User'), ('global', 'Global')], max_length=10),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='scope',
            field=models.CharField(choices=[('user', 'User'), ('global', 'Global')], default='user', max_length=10),
        ),
    ]
