# Generated by Django 6.0.7 on 2026-08-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0065_localize_site_content_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='analytics_share_url',
            field=models.URLField(blank=True, help_text='Analytics sharing URL (for example, Umami or Google Analytics)', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('EDITOR', 'Author')], default='READER', help_text='User role (Reader: read only; Author: write posts and view analytics)', max_length=10),
        ),
    ]
