# Generated by Django 6.0.7 on 2026-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0066_localize_profile_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='message_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notify',
            name='message_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
