"""Legacy session-authenticated v1 API routes."""

from django.urls import path

from board.views.api import v1 as api_v1


urlpatterns = [
    path('v1/login', api_v1.login),
    path('v1/logout', api_v1.logout),
    path('v1/sign', api_v1.sign),
    path('v1/sign/<social>', api_v1.sign_social),
    path('v1/social-providers', api_v1.social_providers),
    path('v1/auth/security', api_v1.security),
    path('v1/auth/security/verify', api_v1.security_verify),
    path('v1/developer-tokens', api_v1.developer_tokens),
    path('v1/developer-tokens/<int:token_id>', api_v1.developer_tokens),
    path('v1/setting/<path:parameter>', api_v1.setting),
    path('v1/search', api_v1.search),
    path('v1/posts', api_v1.post_list),
    path('v1/posts/<url>/comments', api_v1.post_comment_list),
    path('v1/drafts', api_v1.drafts_list),
    path('v1/drafts/<url>', api_v1.drafts_detail),
    path('v1/comments', api_v1.comment_list),
    path('v1/comments/user', api_v1.user_comment),
    path('v1/comments/<int:id>', api_v1.comment_detail),
    path('v1/users/@<username>/heatmap', api_v1.get_author_heatmap),
    path('v1/users/@<username>', api_v1.users),
    path('v1/users/@<username>/posts/<url>', api_v1.user_posts),
    path(
        'v1/users/@<username>/posts/<url>/revisions',
        api_v1.post_revisions,
    ),
    path(
        'v1/users/@<username>/posts/<url>/revisions/<int:revision_id>',
        api_v1.post_revisions,
    ),
    path(
        'v1/users/@<username>/posts/<url>/revisions/<int:revision_id>/restore',
        api_v1.restore_post_revision,
    ),
    path(
        'v1/users/@<username>/posts/<url>/schedule/cancel',
        api_v1.cancel_post_schedule,
    ),
    path(
        'v1/users/@<username>/posts/<url>/schedule/publish-now',
        api_v1.publish_scheduled_post_now,
    ),
    path('v1/users/@<username>/posts/<url>/related', api_v1.user_post_related),
    path('v1/users/@<username>/series', api_v1.user_series),
    path('v1/users/@<username>/series/<url>', api_v1.user_series),
    path('v1/users/@<username>/check-redirect', api_v1.check_redirect),
    path('v1/users/@<username>/pinned-posts', api_v1.pinned_posts),
    path('v1/users/@<username>/pinned-posts/order', api_v1.pinned_posts_order),
    path('v1/users/@<username>/pinnable-posts', api_v1.pinnable_posts),
    path('v1/series', api_v1.series_create_update),
    path('v1/series/<int:series_id>', api_v1.series_detail),
    path('v1/series/valid-posts', api_v1.posts_can_add_series),
    path('v1/series/order', api_v1.series_order),
    path('v1/report/error', api_v1.error_report),
    path('v1/image', api_v1.image),
    path('v1/forms', api_v1.forms_list),
    path('v1/forms/<int:id>', api_v1.forms_detail),
    path('v1/telegram/<parameter>', api_v1.telegram),
    path('v1/banners', api_v1.banner),
    path('v1/banners/order', api_v1.banner_order),
    path('v1/banners/<int:banner_id>', api_v1.banner),
    path('v1/notices', api_v1.notices),
    path('v1/notices/<int:notice_id>', api_v1.notices),
    path('v1/global-notices', api_v1.global_notices),
    path('v1/global-notices/<int:notice_id>', api_v1.global_notices),
    path('v1/global-banners', api_v1.global_banners),
    path('v1/global-banners/order', api_v1.global_banner_order),
    path('v1/global-banners/<int:banner_id>', api_v1.global_banners),
    path('v1/site-settings', api_v1.site_settings),
    path('v1/site-settings/brand-assets', api_v1.site_setting_brand_assets),
    path('v1/login-settings', api_v1.login_settings),
    path('v1/integration-settings', api_v1.integration_settings),
    path('v1/static-pages', api_v1.static_pages),
    path('v1/static-pages/<int:page_id>', api_v1.static_pages),
    path('v1/markdown', api_v1.markdown_to_html),
    path('v1/admin/users', api_v1.managed_users),
    path('v1/admin/users/<int:user_id>/role', api_v1.managed_user_role),
    path('v1/admin/author-invites', api_v1.author_invites),
    path('v1/admin/author-invites/<int:invite_id>', api_v1.author_invite_detail),

    # Utility endpoints
    path('v1/utilities/stats', api_v1.utility_stats),
    path('v1/utilities/clean-tags', api_v1.utility_clean_tags),
    path('v1/utilities/clean-sessions', api_v1.utility_clean_sessions),
    path('v1/utilities/clean-logs', api_v1.utility_clean_logs),
    path('v1/utilities/clean-images', api_v1.utility_clean_images),

    # Webhook channels (author's notification channels)
    path('v1/webhook/channels', api_v1.my_channels),
    path('v1/webhook/channels/<int:channel_id>', api_v1.delete_channel),
    path('v1/webhook/global-channels', api_v1.global_channels),
    path('v1/webhook/global-channels/<int:channel_id>', api_v1.delete_global_channel),
    path('v1/webhook/test', api_v1.test_channel),
]
