name: CI BE

on:
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/src/**'
  workflow_dispatch:

jobs:
  backend_ci:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Load .env file
      uses: xom9ikk/dotenv@v2.2.0
      with:
        path: dev-tools/sample/backend

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend/src

    - name: Test
      run: |
        python manage.py test --verbosity 2
      working-directory: backend/src
