name: CI FE

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Load .env file
      uses: xom9ikk/dotenv@v1.0.2
      with:
        path: dev-tools/sample/frontend

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm i
      working-directory: frontend/src
    
    - name: Lint
      run: npm run eslint
      working-directory: frontend/src
    
    - name: Test
      run: npm run test
      working-directory: frontend/src
    
    - name: Build
      run: npm run build
      working-directory: frontend/src
